/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/turns/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Turn */
        post: operations["new_turn_api_turns_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/fold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fold */
        post: operations["fold_api_turns_fold_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/select-option": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Option */
        post: operations["select_option_api_turns_select_option_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/set-custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Custom */
        post: operations["set_custom_api_turns_set_custom_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/answer-custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Custom */
        post: operations["answer_custom_api_turns_answer_custom_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/submit-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Form */
        post: operations["submit_form_api_turns_submit_form_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/drop-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drop Form */
        post: operations["drop_form_api_turns_drop_form_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/render-running": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Running */
        post: operations["render_running_api_turns_render_running_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/render-think": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Think */
        post: operations["render_think_api_turns_render_think_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/render-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Result */
        post: operations["render_result_api_turns_render_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/render-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Diff */
        post: operations["render_diff_api_turns_render_diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/telegram-html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Html */
        post: operations["telegram_html_api_turns_telegram_html_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/plain-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plain Text */
        post: operations["plain_text_api_turns_plain_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Split */
        post: operations["split_api_turns_split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/redact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redact */
        post: operations["redact_api_turns_redact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/safe-filename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Safe Filename */
        post: operations["safe_filename_api_turns_safe_filename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/media-note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Media Note */
        post: operations["media_note_api_turns_media_note_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/media-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media Limits */
        get: operations["media_limits_api_turns_media_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/battery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Battery */
        get: operations["battery_api_battery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funnel/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_funnel_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funnel/on": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** On */
        post: operations["on_api_funnel_on_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funnel/off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Off */
        post: operations["off_api_funnel_off_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/render/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Markdown */
        post: operations["markdown_api_render_markdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerCustomRequest */
        AnswerCustomRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @default
             */
            request_id: string;
            /**
             * Qidx
             * @default 0
             */
            qidx: number;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** BatteryResponse */
        BatteryResponse: {
            /** Capacity */
            capacity?: string | null;
            /** Status */
            status?: string | null;
            /** Health */
            health?: string | null;
            /** Technology */
            technology?: string | null;
            /** Voltage Now */
            voltage_now?: string | null;
            /** Current Now */
            current_now?: string | null;
            /** Temp */
            temp?: string | null;
            /**
             * Formatted
             * @default
             */
            formatted: string;
        };
        /** DropFormRequest */
        DropFormRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @default
             */
            request_id: string;
        };
        /** FoldDetail */
        FoldDetail: {
            /** Reason */
            reason?: string | null;
            /** Error */
            error?: string | null;
            /** Tool Phase */
            tool_phase?: string | null;
            /** Tool Id */
            tool_id?: string | null;
            /** Diff Path */
            diff_path?: string | null;
        };
        /** FoldRequest */
        FoldRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /** Event */
            event?: {
                [key: string]: unknown;
            };
        };
        /** FoldResponse */
        FoldResponse: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /** Action */
            action: string;
            detail?: components["schemas"]["FoldDetail"] | null;
        };
        /** FormAnswerResponse */
        FormAnswerResponse: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Complete
             * @default false
             */
            complete: boolean;
            /** Answer */
            answer?: {
                [key: string]: unknown;
            };
            /** Missing */
            missing?: number[];
        };
        /** FunnelActionResponse */
        FunnelActionResponse: {
            /**
             * Ok
             * @default false
             */
            ok: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** FunnelEntry */
        FunnelEntry: {
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * On
             * @default false
             */
            on: boolean;
            /** Mappings */
            mappings?: string[];
        };
        /** FunnelStatusResponse */
        FunnelStatusResponse: {
            /**
             * Raw
             * @default
             */
            raw: string;
            /** Funnels */
            funnels?: components["schemas"]["FunnelEntry"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HtmlResponse */
        HtmlResponse: {
            /**
             * Html
             * @default
             */
            html: string;
        };
        /** MediaLimitsResponse */
        MediaLimitsResponse: {
            /**
             * Max Bytes
             * @default 0
             */
            max_bytes: number;
            /** Fallback Mime */
            fallback_mime?: {
                [key: string]: string;
            };
        };
        /** MediaNoteRequest */
        MediaNoteRequest: {
            /**
             * Kind
             * @default download_failed
             */
            kind: string;
            /**
             * Filename
             * @default anexo
             */
            filename: string;
            /**
             * Size Mb
             * @default 0
             */
            size_mb: number;
        };
        /** NewTurnRequest */
        NewTurnRequest: {
            /**
             * Chat Id
             * @default 0
             */
            chat_id: number;
        };
        /** NewTurnResponse */
        NewTurnResponse: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
        };
        /** PlainTextRequest */
        PlainTextRequest: {
            /**
             * Html
             * @default
             */
            html: string;
        };
        /** RedactRequest */
        RedactRequest: {
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** RenderDiffRequest */
        RenderDiffRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Opencode Dir
             * @default
             */
            opencode_dir: string;
        };
        /** RenderMarkdownRequest */
        RenderMarkdownRequest: {
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** RenderMarkdownResponse */
        RenderMarkdownResponse: {
            /**
             * Html
             * @default
             */
            html: string;
        };
        /** RenderResultRequest */
        RenderResultRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
        };
        /** RenderRunningRequest */
        RenderRunningRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Opencode Dir
             * @default
             */
            opencode_dir: string;
        };
        /** RenderRunningResponse */
        RenderRunningResponse: {
            /**
             * Text
             * @default
             */
            text: string;
            /** Keyboard */
            keyboard?: components["schemas"]["TurnButton"][][];
        };
        /** RenderThinkRequest */
        RenderThinkRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Elapsed
             * @default 0
             */
            elapsed: number;
            /**
             * Opencode Dir
             * @default
             */
            opencode_dir: string;
        };
        /** SafeFilenameRequest */
        SafeFilenameRequest: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Default
             * @default arquivo.bin
             */
            default: string;
        };
        /** SafeFilenameResponse */
        SafeFilenameResponse: {
            /**
             * Filename
             * @default
             */
            filename: string;
        };
        /** SelectOptionRequest */
        SelectOptionRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @default
             */
            request_id: string;
            /**
             * Qidx
             * @default 0
             */
            qidx: number;
            /**
             * Opt
             * @default 0
             */
            opt: number;
        };
        /** SelectOptionResponse */
        SelectOptionResponse: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Changed
             * @default false
             */
            changed: boolean;
        };
        /** SetCustomRequest */
        SetCustomRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @default
             */
            request_id: string;
            /**
             * Qidx
             * @default 0
             */
            qidx: number;
        };
        /** SplitRequest */
        SplitRequest: {
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Limit
             * @default 4000
             */
            limit: number;
        };
        /** SplitResponse */
        SplitResponse: {
            /** Chunks */
            chunks?: string[];
        };
        /** SubmitFormRequest */
        SubmitFormRequest: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @default
             */
            request_id: string;
        };
        /** TelegramHtmlRequest */
        TelegramHtmlRequest: {
            /**
             * Text
             * @default
             */
            text: string;
            /** Max Len */
            max_len?: number | null;
        };
        /** TextResponse */
        TextResponse: {
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** TurnButton */
        TurnButton: {
            /** Text */
            text: string;
            /** Data */
            data: string;
        };
        /** TurnPayload */
        TurnPayload: {
            /** Turn */
            turn: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    new_turn_api_turns_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fold_api_turns_fold_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoldRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_option_api_turns_select_option_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectOptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelectOptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_custom_api_turns_set_custom_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCustomRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_custom_api_turns_answer_custom_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerCustomRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_form_api_turns_submit_form_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitFormRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drop_form_api_turns_drop_form_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DropFormRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_running_api_turns_render_running_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRunningRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRunningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_think_api_turns_render_think_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderThinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_result_api_turns_render_result_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderResultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_diff_api_turns_render_diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderDiffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_html_api_turns_telegram_html_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramHtmlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HtmlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plain_text_api_turns_plain_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlainTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_api_turns_split_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redact_api_turns_redact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    safe_filename_api_turns_safe_filename_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafeFilenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafeFilenameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_note_api_turns_media_note_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_limits_api_turns_media_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaLimitsResponse"];
                };
            };
        };
    };
    battery_api_battery_get: {
        parameters: {
            query?: {
                battery_path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatteryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_funnel_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelStatusResponse"];
                };
            };
        };
    };
    on_api_funnel_on_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelActionResponse"];
                };
            };
        };
    };
    off_api_funnel_off_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelActionResponse"];
                };
            };
        };
    };
    markdown_api_render_markdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderMarkdownRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderMarkdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
